spring:
  cloud:
    bus:
      enabled: true

security:
  oauth2:
    client:
      clientId: '{cipher}AQCcrThGaQh7ow1NllU9mAJLbiuUJyIkkwSZw/aL2P9s5trLi44+p+XWa+yCvRlKJ/GWnaf6bJ8e3fcxQ9S0CONPuUPMcCuqtF/e8Lg5wy+BYTmrSkcUI/PY3Tcaorn86cDbhKY3HaFhzWs1nH9HUHRxg1lc1dHmgGWNmBHD+RDrXrIJabzoc1vkY1z+KYxFRfEKHc1waHda7L6aepGsU8Zod4XupZWkzO2mQep+exkYymYiQuJ12C2iUVBAeRD6ygmODMm1Gh4W6dw39aGmTTt1tyU5nrLXccQrWtnZbpIdDJpHsRmgwpYM/2c9KM8TpbW86B0UJvtKpVgcy/e9vfUPCTX+bmXyGxE9CmYvKbnY/B0oYTAGF9JyKwFW+FzN4jA='
      clientSecret: '{cipher}AQCcrThGaQh7ow1NllU9mAJLbiuUJyIkkwSZw/aL2P9s5trLi44+p+XWa+yCvRlKJ/GWnaf6bJ8e3fcxQ9S0CONPuUPMcCuqtF/e8Lg5wy+BYTmrSkcUI/PY3Tcaorn86cDbhKY3HaFhzWs1nH9HUHRxg1lc1dHmgGWNmBHD+RDrXrIJabzoc1vkY1z+KYxFRfEKHc1waHda7L6aepGsU8Zod4XupZWkzO2mQep+exkYymYiQuJ12C2iUVBAeRD6ygmODMm1Gh4W6dw39aGmTTt1tyU5nrLXccQrWtnZbpIdDJpHsRmgwpYM/2c9KM8TpbW86B0UJvtKpVgcy/e9vfUPCTX+bmXyGxE9CmYvKbnY/B0oYTAGF9JyKwFW+FzN4jA='
    resource:
      token-info-uri: http://oauth-server/oauth/check_token
message:
  invalid_access_token: Invalid access token.
  access_denied: User is not authorized to access the requested resource.
  event_add_success: Your event has been created successfully.
  event_add_failed: Unable to add event.
  event_update_success: Your event details has been updated successfully.
  event_update_failed: Unable to update event.
  event_invitations_sent_success: Invitations has been sent successfully.
  event_invitations_sent_failed: Failed to send invitations.
  invitation_status_update_success: Thank you for your Response.
  invitation_status_update_failed: We are not able to take your response currently.
  event_venue_add_success: Your venue has been created successfully.
  event_venue_add_failed: Failed to add new Venue;
url:
  invitation-status-update: http://localhost:4200/#/app/invitations/{invitationId}/status/{token}
